version: 2

# DEFAULTS FOR JOBS
default job config: &defaults
  working_directory: ~/async_storage
  
checkout step for each job: &addWorkspace
  attach_workspace:
    at: ~/async_storage


# ENVIRONMENT DEFAULTS

default config for js: &js_defaults
  <<: *defaults
  docker:
    - image: circleci/node:8

default config for macOS: &macos_defaults
  <<: *defaults
  resource_class: 'medium'
  macos:
    xcode: '10.1.0'


# CACHE SETTINGS
save brew cache: &cache_save_brew
  paths:
    - /usr/local/Homebrew
    - ~/Library/Caches/Homebrew
  key: v1-brew-cache-{{ arch }}

restore brew cache: &cache_restore_brew
  keys:
    - v1-brew-cache-{{ arch }}

save yarn cache: &cache_save_yarn
  paths:
    - ~/.cache/yarn
    - ~/Library/Detox
  key: v1-yarn-cache-{{ checksum "package.json" }}-{{ arch }}

restore yarn cache: &cache_restore_yarn
  keys: 
    - v1-yarn-cache-{{ checksum "package.json" }}-{{ arch }}

# JOBS

jobs:

  "Setup environment":
    <<: *js_defaults
    steps:
      - checkout
      - restore-cache: *cache_restore_yarn
      - run:
          name: Install dependencies
          command: yarn --pure-lockfile --non-interactive --cache-folder ~/.cache/yarn
      - save-cache: *cache_save_yarn
      - persist_to_workspace:
          root: .
          paths: .

  "Test: lint":
    <<: *js_defaults
    steps:
      - *addWorkspace
      - run:
          name: Lint check
          command: yarn test:lint

  "Test: flow":
    <<: *js_defaults
    steps:
      - *addWorkspace
      - run:
          name: Flow check
          command: yarn test:flow

  "Test: iOS e2e":
    <<: *macos_defaults
    steps:
      - *addWorkspace
      - restore-cache: *cache_restore_brew
      - run:
          name: Configure OSX Environment
          command: |
            HOMEBREW_NO_AUTO_UPDATE=1 brew install node@8 >/dev/null
            HOMEBREW_NO_AUTO_UPDATE=1 brew tap wix/brew >/dev/null
            HOMEBREW_NO_AUTO_UPDATE=1 brew install applesimutils >/dev/null
            touch .watchmanconfig
            node -v
      - save-cache: *cache_save_brew
      - restore-cache: *cache_restore_yarn
      - run: 
          name: Ensure dotex post install
          command: yarn --pure-lockfile --non-interactive --cache-folder ~/.cache/yarn
      - save-cache: *cache_save_yarn
      - run:
          name: Build iOS app
          command: yarn build:e2e:ios

      - run:
          name: Run e2e tests
          command: yarn test:e2e:ios

workflows:
  version: 2
  "Testing":
    jobs:
      - "Setup environment"
      - "Test: lint":
          requires:
            - "Setup environment"
      - "Test: flow":
          requires:
            - "Setup environment"
      - "Test: iOS e2e":
          requires:
            - "Test: lint"
            - "Test: flow"